services:
  - type: web
    name: discordbot-musicologo
    runtime: node
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: Client_ID
        sync: false
