services:
  - type: web
    name: discordbot-musicologo
    runtime: node
    buildCommand: npm install
    startCommand: node src/app.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: Client_ID
        sync: false

  - type: static
    name: musicologo-landing
    buildCommand: cd web && npm install && npm run build
    staticPublishPath: web/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
